highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
gems:
  - jekyll-sitemap
permalink: blogs/:title/
title: krishna.log
description: Ooo, whomst have stumbled upon Krishna's website?
keywords: krishna, security, github, iit, patna, web, njack
baseurl: ""
url: https://lordlabuckdas.github.io
author: krishna
google-site-verif: TuEKuF1sEBI7ReAjZVknGSNpEOTTHeAu6GqbmmFCN40
