title: krishna.log
description: personal website of krishna
keywords: krishna, github, iit, patna, blog, log, lordlabuckdas
author: Krishna
url: https://lordlabuckdas.github.io
permalink: blog/:title/
urls:
  github: https://github.com/lordlabuckdas
  linkedin: https://in.linkedin.com/in/krishnan11
icons:
  github: /img/github.gif
  linkedin: /img/linkedin.gif
  rss: /img/rss.gif
  favicon: /img/favicon.ico
plugins:
  - github-pages
  - jekyll-sitemap
  - jekyll-minifier
jekyll-minifier:
  exclude: atom.xml
