highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
gems:
  - jekyll-sitemap
permalink: blogs/:title/
title: krishna.log
# email: me@dhavalkapil.com
# description: Website of Dhaval Kapil, graduate student at Georgia Tech
description: Ooo, whomst have stumbled upon Krishna's website?
keywords: krishna, security, github, iit, patna, web, njack
baseurl: ""
url: https://lordlabuckdas.github.io
name: krishna\'s blog
author:
  name: krishna
